---
title: "Your Name Here"
author: "Your Affiliation Here"
output: html_document
---
<hr>

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, error=FALSE}
# Your XML file.
myLattes  <- "curriculo.xml"

# Load (and, if needed, install) the required packages
if (!("XML" %in% rownames(installed.packages()))) install.packages("XML")
require("XML", character.only = TRUE)

# Function to easily capitalize author lists
.simpleCap <- function(x) {
    s <- strsplit(x, " ")[[1]]
    s <- paste(toupper(substring(s, 1, 1)), tolower(substring(s, 2)),
               sep = "", collapse = " ")
    s <- gsub(pattern     = " De ", 
              replacement = " de ", 
              x           = s)
    s <- gsub(pattern     = " Da ", 
              replacement = " da ", 
              x           = s)
    return(s)
}

# Function to get author names in "Name Surname" format
.authorname <- function(x){
    s <- strsplit(x, ",")[[1]]
    if (length(s) == 2) s <- paste(s[2], s[1])
    sub("^\\s+", "", s)
}


# Read XML to a list object
doc <- XML::xmlToList(XML::xmlTreeParse(myLattes, 
                                        useInternal = TRUE, 
                                        encoding    = "latin"))

# Get published journal papers
npap     <- length(doc$`PRODUCAO-BIBLIOGRAFICA`$`ARTIGOS-PUBLICADOS`)
MyPapers <- data.frame(Authors = character(npap),
                       Title   = character(npap),
                       Journal = character(npap),
                       Volume  = character(npap),
                       Issue   = character(npap),
                       Pages   = character(npap),
                       Year    = character(npap),
                       DOI     = character(npap),
                       stringsAsFactors = FALSE)

# Probably more effective if I used lapply, but more didactic with a for loop
for (i in 1:npap){
    paper <- doc$`PRODUCAO-BIBLIOGRAFICA`$`ARTIGOS-PUBLICADOS`[[i]]
    MyPapers$Title[i]   <- paper$`DADOS-BASICOS-DO-ARTIGO`[[2]]
    MyPapers$Journal[i] <- paper$`DETALHAMENTO-DO-ARTIGO`[[1]]
    MyPapers$Volume[i]  <- paper$`DETALHAMENTO-DO-ARTIGO`[[3]]
    MyPapers$Issue[i]   <- ifelse(paper$`DETALHAMENTO-DO-ARTIGO`[[5]] == "", 
                                  yes = "1",
                                  no  = paper$`DETALHAMENTO-DO-ARTIGO`[[5]])
    MyPapers$Pages[i]   <- paste0(paper$`DETALHAMENTO-DO-ARTIGO`[[6]],
                                  "-",
                                  paper$`DETALHAMENTO-DO-ARTIGO`[[7]])
    MyPapers$Year[i]    <- paper$`DADOS-BASICOS-DO-ARTIGO`[[3]]
    MyPapers$DOI[i]     <- ifelse(paper$`DADOS-BASICOS-DO-ARTIGO`[[9]] == "",
                                  sample.int(100000000, 1),
                                  paper$`DADOS-BASICOS-DO-ARTIGO`[[9]])
    
    authindx            <- which(names(paper) == "AUTORES")
    nauthors            <- length(authindx)
    MyPapers$Authors[i] <- .authorname(paper[[authindx[1]]][1])
    if (nauthors > 1){
        for (j in 2:nauthors){
            MyPapers$Authors[i] <- paste0(MyPapers$Authors[i], 
                                          ", ",
                                          .authorname(paper[[authindx[j]]][1]))
        }
    }
    
    # Get author list with correct case
    MyPapers$Authors[i] <- .simpleCap(MyPapers$Authors[i])
    
    # Replace my (Felipe's) full name with my publication alias. Change if needed, comment if irrelevant
    MyPapers$Authors[i] <-gsub(pattern     = "Felipe Campelo Franca Pinto", 
                               replacement = "Felipe Campelo", 
                               x           = MyPapers$Authors[i])
}

# ==========================================

# Get conference papers
npap    <- length(doc$`PRODUCAO-BIBLIOGRAFICA`$`TRABALHOS-EM-EVENTOS`)
MyConfs <- data.frame(Authors    = character(npap),
                      Title      = character(npap),
                      Conference = character(npap),
                      Country    = character(npap),
                      Pages      = character(npap),
                      Year       = character(npap),
                      stringsAsFactors = FALSE)

for (i in 1:npap){
    paper <- doc$`PRODUCAO-BIBLIOGRAFICA`$`TRABALHOS-EM-EVENTOS`[[i]]
    MyConfs$Title[i]      <- paper$`DADOS-BASICOS-DO-TRABALHO`[[2]]
    MyConfs$Conference[i] <- paper$`DETALHAMENTO-DO-TRABALHO`[[2]]
    MyConfs$Country[i]    <- paper$`DADOS-BASICOS-DO-TRABALHO`[[4]]
    MyConfs$Year[i]       <- max(paper$`DETALHAMENTO-DO-TRABALHO`[[4]],
                                 paper$`DADOS-BASICOS-DO-TRABALHO`[[3]])
    MyConfs$Pages[i]      <- paste0(paper$`DETALHAMENTO-DO-TRABALHO`[[9]],
                                    "-",
                                    paper$`DETALHAMENTO-DO-TRABALHO`[[10]])
    authindx              <- which(names(paper) == "AUTORES")
    nauthors              <- length(authindx)
    MyConfs$Authors[i]    <- .authorname(paper[[authindx[1]]][1])
    if (nauthors > 1){
        for (j in 2:nauthors){
            MyConfs$Authors[i] <- paste0(MyConfs$Authors[i], 
                                         ", ",
                                         .authorname(paper[[authindx[j]]][1]))
        }
    }
    
    # Get author list with correct case
    MyConfs$Authors[i] <- .simpleCap(MyConfs$Authors[i])
    
    # Replace my (Felipe's) full name with my publication alias. Change if needed, comment if irrelevant
    MyConfs$Authors[i] <-gsub(pattern     = "Felipe Campelo Franca Pinto", 
                              replacement = "Felipe Campelo", 
                              x           = MyConfs$Authors[i])
}

# ==========================================

# Get book chapters
npap    <- length(doc$`PRODUCAO-BIBLIOGRAFICA`$`LIVROS-E-CAPITULOS`$`CAPITULOS-DE-LIVROS-PUBLICADOS`)
MyChaps <- data.frame(Authors  = character(npap),
                      Title    = character(npap),
                      Bookname = character(npap),
                      Volume   = character(npap),
                      Pages    = character(npap),
                      Year     = character(npap),
                      stringsAsFactors = FALSE)

if (npap){
    for (i in 1:npap){
        paper <- doc$`PRODUCAO-BIBLIOGRAFICA`$`LIVROS-E-CAPITULOS`$`CAPITULOS-DE-LIVROS-PUBLICADOS`[[i]]
        MyChaps$Title[i]    <- paper$`DADOS-BASICOS-DO-CAPITULO`[[2]]
        MyChaps$Bookname[i] <- paper$`DETALHAMENTO-DO-CAPITULO`[[1]]
        MyChaps$Volume[i]   <- paper$`DETALHAMENTO-DO-CAPITULO`[[2]]
        MyChaps$Year[i]     <- paper$`DADOS-BASICOS-DO-CAPITULO`[[3]]
        MyChaps$Pages[i]    <- paste0(paper$`DETALHAMENTO-DO-CAPITULO`[[3]],
                                      "-",
                                      paper$`DETALHAMENTO-DO-CAPITULO`[[4]])
        authindx            <- which(names(paper) == "AUTORES")
        nauthors            <- length(authindx)
        MyChaps$Authors[i]  <- .authorname(paper[[authindx[1]]][1])
        if (nauthors > 1){
            for (j in 2:nauthors){
                MyChaps$Authors[i] <- paste0(MyChaps$Authors[i], 
                                             ", ",
                                             .authorname(paper[[authindx[j]]][1]))
            }
        }
        
        # Get author list with correct case
        MyChaps$Authors[i] <- .simpleCap(MyChaps$Authors[i])
        
        # Replace my (Felipe's) full name with my publication alias. Change if needed, comment if irrelevant
        MyChaps$Authors[i] <-gsub(pattern     = "Felipe Campelo Franca Pinto", 
                                  replacement = "Felipe Campelo", 
                                  x           = MyChaps$Authors[i])
        
        # ==========================================
    }
}

# Sort: most recent first
MyPapers <- MyPapers[order(MyPapers$Year, decreasing = TRUE), ]
MyConfs  <- MyConfs[order(MyConfs$Year, decreasing = TRUE), ]
MyChaps  <- MyChaps[order(MyChaps$Year, decreasing = TRUE), ]

```

## Journal Papers  
  
```{r, results='asis',echo=FALSE}
# Assemble list of papers
for (i in 1:nrow(MyPapers)){
    cat(i, ". ",
        MyPapers$Authors[i], ": _",
        MyPapers$Title[i], "._ ",
        MyPapers$Journal[i], " ",
        MyPapers$Volume[i], "(",
        MyPapers$Issue[i], "):",
        MyPapers$Pages[i], ", ",
        MyPapers$Year[i], ".<br/>",
        "[[DOI: ", 
        MyPapers$DOI[i],
        "](http://dx.doi.org/",
        MyPapers$DOI[i],")]\n\n<hr>  ",
        sep = "")
}
```

## Book Chapters  
  
```{r, results='asis',echo=FALSE}
# Assemble list of book chapters
for (i in 1:nrow(MyChaps)){
    cat(i, ". ",
        MyChaps$Authors[i], ": _",
        MyChaps$Title[i], "._ In: ",
        MyChaps$Bookname[i], 
        " v. ", MyChaps$Volume[i], 
        ", pp. ", MyChaps$Pages[i], ", ",
        MyChaps$Year[i],
        "\n\n<hr>  ",
        sep = "")
}
```

## Conference Proceedings  
  
```{r, results='asis',echo=FALSE}
# Assemble list of conference papers
for (i in 1:nrow(MyConfs)){
    cat(i, ". ",
        MyConfs$Authors[i], ": _",
        MyConfs$Title[i], "._ ",
        MyConfs$Conference[i], ", ",
        MyConfs$Year[i], ". ",
        "pp. ", MyConfs$Pages[i], ".",
        "\n\n<hr>  ",
        sep = "")
}
```

<div style="background-color:#eeeeee; width:600px">
Last updated: `r Sys.Date()`<br/>
Generated with [Lattes XML to HTML](https://github.com/fcampelo/Lattes-XML-to-HTML) by [Felipe Campelo](mailto:fcampelo@ufmg.br)<br/>
ORCS Lab - Operational Research and Complex Systems Laboratory<br/>
Department of Electrical Engineering, Universidade Federal de Minas Gerais<br/>
Belo Horizonte, Brazil</i>
</div>
