#' Plot summary chart
#'
#' Plot summary chart from a Lattes list object
#'
#' This function plots production information from a Lattes list object
#' generated by [lattes_to_list()]:
#' - Accepted journal papers
#' - Published journal papers
#' - Published conference papers
#' - Published book chapters
#' - Published books
#' - Ph.D. student defenses
#' - M.Sc. student defenses
#'
#' @param lattes.list a Lattes list object created using [lattes_to_list()]
#' @param chart.type package to use for generating the summary chart. "plotly" and
#' "rCharts" output interactive charts, "ggplot2" outputs a static one.
#' @param width plot width (for "plotly" and "rCharts")
#' @param height plot height (for "plotly")
#'
#' @return plot object for inclusion in a productions page
#' (see [make_productions_page()].

plot_chart <- function(lattes.list,
                       chart.type = c("ggplot2","plotly","rCharts"),
                       width  = 960,
                       height = 480){

  # Match argument
  type <- match.arg(chart.type, c("ggplot2","plotly","rCharts"))

  # preprocess lattes.list
  lattes.list$`Conference Papers - International` <- lattes.list$`Conference Papers`[which(lattes.list$`Conference Papers`$Internac), ]
  lattes.list$`Conference Papers - National`      <- lattes.list$`Conference Papers`[which(!lattes.list$`Conference Papers`$Internac), ]
  lattes.list$`Conference Papers`                 <- NULL

  # Assemble data frame with total counts per year
  myTotals              <- lapply(lattes.list,
                                  function(x){as.data.frame(table(x$Year))})
  myTotals              <- do.call(rbind.data.frame, myTotals)
  myTotals$Type         <- gsub("\\..*","", rownames(myTotals))
  names(myTotals)       <- c("Year", "Count", "Type")
  myTotals$Year         <- as.numeric(as.character(myTotals$Year))
  myTotals              <- myTotals[order(myTotals$Year), ]
  rownames(myTotals)    <- paste0(myTotals$Year, myTotals$Type)

  # Second data frame containing all entries by year (even if with 0 occurrences)
  myTotals2          <- with(myTotals,
                             expand.grid(Year     = unique(Year),
                                         Type     = unique(Type)))
  myTotals2$Count    <- 0
  rownames(myTotals2) <- paste0(myTotals2$Year, myTotals2$Type)

  # Populate counts for myTotals2
  for (i in 1:nrow(myTotals)){
    indx <- which(rownames(myTotals2) == rownames(myTotals)[i])
    if(length(indx)){
      myTotals2$Count[indx] <- myTotals$Count[i]
    }
  }


  ## Using ggplot2 (+ plotly if specified)
  if (type == "ggplot2" | type == "plotly"){
    myPlot <- ggplot2::ggplot(data    = myTotals2,
                              mapping = ggplot2::aes(x     = Year,
                                                     y     = Count,
                                                     fill  = Type)) +
      ggplot2::geom_bar(stat     = "identity",
                        position = "stack",
                        colour   = "#00000011") +
      ggplot2::scale_x_continuous(breaks = min(myTotals2$Year):max(myTotals2$Year)) +
      ggplot2::theme(axis.text.x     = ggplot2::element_text(angle = 45, vjust = 0),
                     legend.position = "bottom")


    if (type == "plotly"){
      myPlot <- plotly::ggplotly(myPlot,
                                 width  = width,
                                 height = height)
    }
    return(myPlot)
  }

  if(type == "rCharts"){
    # Check if rCharts and RColorBrewer are installed
    if(!("rCharts" %in% rownames(installed.packages()))){
      stop("Please install rCharts 0.4.5 using\n> devtools::install_github(repo = 'ramnathv/rCharts', ref = '479a4f9')")
    }
    if(!("RColorBrewer" %in% rownames(installed.packages()))){
      stop("Please install RColorBrewer using\n> install.packages('RColorBrewer')")
    }

    # Using rCharts
    TotalsPlot <- rCharts::nPlot(Count ~ Year,
                                 group = "Type",
                                 data  = myTotals2,
                                 type  = "multiBarChart")
    # Add decorations and customize style
    TotalsPlot$chart(color            = RColorBrewer::brewer.pal(8, "Set1"),
                     reduceXTicks     = FALSE)
    TotalsPlot$xAxis(rotateLabels     = -45,
                     staggerLabels    = FALSE)
    TotalsPlot$chart(multibar.stacked = TRUE)
    TotalsPlot$set(width = width)
    TotalsPlot$print('iframesrc', include_assets = TRUE)
  }
}
